/* eslint-disable react/no-unescaped-entities */
import { Box } from '@mui/material'
import Head from 'next/head'
import type { ReactNode } from 'react'

import {
	HomeContent,
	MainContent,
	MainHero,
	MainLayout
} from '@/components/index'

const Home: {
	(): JSX.Element
	getLayout(page: ReactNode): JSX.Element
} = () => {
	return (
		<div>
			<Head>
				<title>Todo App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Box
				sx={{
					display: 'flex',
					height: '100vh'
				}}
			>
				<MainHero path='/hero.jpg' />
				<MainContent>
					<HomeContent />
				</MainContent>
			</Box>
		</div>
	)
}

export default Home

Home.getLayout = page => <MainLayout>{page}</MainLayout>
