/* eslint-disable react/no-unescaped-entities */
import { Box } from '@mui/material'
import type { NextPageWithLayout } from 'next'
import Head from 'next/head'
import type { ReactNode } from 'react'

import HomeContent from '@/components/HomeContent'
import MainContent from '@/components/MainContent'
import MainHero from '@/components/MainHero'
import MainLayout from '@/layouts/MainLayout'

const Home: NextPageWithLayout = () => {
	return (
		<div>
			<Head>
				<title>Todo App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Box
				sx={{
					display: 'flex',
					height: '100vh'
				}}
			>
				<MainHero path='/hero.jpg' />
				<MainContent>
					<HomeContent />
				</MainContent>
			</Box>
		</div>
	)
}

export default Home

Home.getLayout = (page: ReactNode) => <MainLayout>{page}</MainLayout>
