name: Test
on:
  push:
    branches: [master, feature/test]
jobs:
  test-with-jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: yarn
      - run: yarn
      - name: test
      - run: yarn test
